
title: Toby Lam's Blog
email: greenone092@gmail.com
description: On mathematics and tech

baseurl: "" 
url: "https://greenone092.github.io/" 
github_username:  greenone092

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  
