
title: Toby Lam's Blog
email: greenone092@gmail.com
description: A blog on mathematics and tech

author:
  name: Toby Lam
  email: "greenone092@gmail.com"

baseurl: "" 
url: "https://www.tobylam.xyz" 
github_username:  greenone092

remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a

minima:
  social_links:
    github: greenone092
    linkedin: toby-lam-3ba386193
    youtube_channel: UCkC3ZMvxMng4xlTXaTb6jgQ
    youtube_channel_name: Toby Lam

# Build settings
markdown: kramdown

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 190
    - width: 620
    - width: 900
    - width: 1140
    - width: 1400
    - width: 1500

kramdown:
  math_engine: katex
