
title: Toby Lam's Blog
email: greenone092@gmail.com
description: On mathematics and tech

baseurl: "" 
url: "https://www.tobylam.xyz" 
github_username:  greenone092

remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a

minima:
  social_links:
    github: greenone092
    linkedin: toby-lam-3ba386193
    youtube_channel: UCkC3ZMvxMng4xlTXaTb6jgQ
    youtube_channel_name: Toby Lam

# Build settings
markdown: kramdown

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 220
    - width: 640
    - width: 860
    - width: 1040
    - width: 1200
    - width: 1340